 app:
   build: nginx
   links:
     - consul
   ports:
     - "80:80"

 node:
   build: .
   links:
     - consul
   environment:
       SERVICE_80_NAME: "app"
       SERVICE_80_TAGS: "production"
       SERVICE_22_TAGS: "ssh"
       SERVICE_22_NAME: "access"
   ports:
     - "80"
     - "22"

   volumes:
     - "$SSH_AUTH_SOCK:/tmp/ssh_auth_sock"

 consul:
   command: -server -bootstrap -advertise 192.168.99.100
   image: progrium/consul:latest
   ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

 registrator:
   command: -ip=192.168.99.100 consul://consul:8500
   image: gliderlabs/registrator:latest
   links:
    - consul
   volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

