 app:
   build: nginx 
   links:
     - consul
   ports:
     - "80:80"

 node:  
   build: .
   links:
     - consul
   environment:
       SERVICE_80_NAME: "http"
       SERVICE_NAME: "app"
       SERVICE_TAGS: "production"
   ports:
     - "80"


 consul:
   command: -server -bootstrap -advertise 172.17.42.1
   image: progrium/consul:latest
   ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

 registrator:
   command: -ip=172.17.42.1 consul://consul:8500
   image: gliderlabs/registrator:latest
   links:
    - consul
   volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"



   

